let x=2;
x =-x;
console.log(x);
let a, b, c, perkalian;
a=98;
b=44;
c=13;
perkalian= a*b*c;
console.log(perkalian);
console.log(1+1);
console.log(4%3);
let kota="sura" + "baya";
console.log(kota);
console.log(4 + 4 + 5 + "8");
console.log("3" - "2");
console.log("3" / 3);
let s = y= z=2+2;
console.log(s);
let inc=7;
inc++;
console.log(inc);
let duc=100;
duc--;
console.log(duc);